# coding:utf8
"""

"""


COUNTRY_DICT = {
    'AE': u'阿联酋',
    'AF': u'阿富汗',
    'AL': u'阿尔巴尼亚',
    'AM': u'亚美尼亚',
    'AO': u'安哥拉',
    'AR': u'阿根廷',
    'AT': u'奥地利',
    'AU': u'澳大利亚',
    'AZ': u'阿塞拜疆',
    'BD': u'孟加拉',
    'BE': u'比利时',
    'BF': u'布基纳法索',
    'BG': u'保加利亚',
    'BH': u'巴林',
    'BI': u'布隆迪',
    'BJ': u'贝宁',
    'BL': u'巴勒斯坦',
    'BN': u'文莱',
    'BO': u'玻利维亚',
    'BR': u'巴西',
    'BW': u'博茨瓦纳',
    'BY': u'白俄罗斯',
    'CA': u'加拿大',
    'CF': u'中非',
    'CG': u'刚果',
    'CH': u'瑞士',
    'CL': u'智利',
    'CM': u'喀麦隆',
    'CN': u'中国',
    'CO': u'哥伦比亚',
    'CR': u'哥斯达黎加',
    'CS': u'捷克',
    'CU': u'古巴',
    'CY': u'塞浦路斯',
    'DE': u'德 国',
    'DK': u'丹麦',
    'DO': u'多米尼加共和国',
    'DZ': u'阿尔及利亚',
    'EC': u'厄瓜多尔',
    'EE': u'爱沙尼亚',
    'EG': u'埃及',
    'ES': u'西班牙',
    'ET': u'埃塞俄比亚',
    'FI': u'芬兰',
    'FJ': u'斐济',
    'FR': u'法国',
    'GA': u'加蓬',
    'GB': u'英国',
    'GD': u'格林纳达',
    'GE': u'格鲁吉亚',
    'GH': u'加纳',
    'GN': u'几内亚',
    'GR': u'希腊',
    'GT': u'危地马拉',
    'HK': u'香港特别行政区',
    'HN': u'洪都拉斯',
    'HU': u'匈牙利',
    'ID': u'印度尼西亚',
    'IE': u'爱尔兰',
    'IL': u'以色列',
    'IN': u'印度',
    'IQ': u'伊拉克',
    'IR': u'伊朗',
    'IS': u'冰岛',
    'IT': u'意大利',
    'JM': u'牙买加',
    'JO': u'约旦',
    'Jp': u'日本',
    'KG': u'吉尔吉斯坦',
    'KH': u'柬埔寨',
    'Kp': u'北朝鲜',
    'KR': u'韩国',
    'KT': u'科特迪瓦共和国',
    'KW': u'科威特',
    'KZ': u'哈萨克',
    'LA': u'老挝',
    'LB': u'黎巴嫩',
    'LC': u'列支敦士登',
    'LK': u'斯里兰卡',
    'LR': u'利比里亚',
    'LT': u'立陶宛',
    'LU': u'卢森堡',
    'LV': u'拉脱维亚',
    'LY': u'利比亚',
    'MA': u'摩洛哥',
    'MC': u'摩纳哥',
    'MD': u'摩尔多瓦',
    'MG': u'马达加斯加',
    'ML': u'马里',
    'MM': u'缅甸',
    'MN': u'蒙古',
    'MO': u'澳门地区',
    'MT': u'马耳他',
    'MU': u'毛里求斯',
    'MW': u'马拉维',
    'MX': u'墨西哥',
    'MY': u'马来西亚',
    'MZ': u'莫桑比克',
    'NA': u'纳米比亚',
    'NE': u'尼日尔',
    'NG': u'尼日利亚',
    'NI': u'尼加拉瓜',
    'NL': u'荷兰',
    'NO': u'挪威',
    'Np': u'尼泊尔',
    'NZ': u'新西兰',
    'OM': u'阿曼',
    'pA': u'巴拿马',
    'pE': u'秘鲁',
    'pG': u'巴布亚新几内亚',
    'pH': u'菲律宾',
    'pK': u'巴基斯坦',
    'pL': u'波兰',
    'pT': u'葡萄牙',
    'pY': u'巴拉圭',
    'QA': u'卡塔尔',
    'RO': u'罗马尼亚',
    'RU': u'俄罗斯',
    'SA': u'沙特阿拉伯',
    'SC': u'塞舌尔',
    'SD': u'苏丹',
    'SE': u'瑞典',
    'SG': u'新加坡',
    'SI': u'斯洛文尼亚',
    'SK': u'斯洛伐克',
    'SM': u'圣马力诺',
    'SN': u'塞内加尔',
    'SO': u'索马里',
    'SY': u'叙利亚',
    'SZ': u'斯威士兰',
    'TD': u'乍得',
    'TG': u'多哥',
    'TH': u'泰国',
    'TJ': u'塔吉克斯坦',
    'TM': u'土库曼',
    'TN': u'突尼斯',
    'TR': u'土耳其',
    'TW': u'台湾省',
    'TZ': u'坦桑尼亚',
    'UA': u'乌克兰',
    'UG': u'乌干达',
    'US': u'美国',
    'UY': u'乌拉圭',
    'UZ': u'乌兹别克',
    'VC': u'圣文森特岛',
    'VE': u'委内瑞拉',
    'VN': u'越南',
    'YE': u'也门',
    'YU': u'南斯拉夫联盟',
    'ZA': u'南非',
    'ZM': u'赞比亚',
    'ZR': u'扎伊尔',
    'ZW': u'津巴布韦',
}


def parse():
    with open('country_code.txt') as f:
        for line in f.readlines():
            l = line.strip()
            if not l or '-' not in l:
                continue
            # print l
            code = l.split('-')[0].strip()
            name = l.split('-')[-1].split('(')[0].strip()
            print "'%s': u'%s'," % (code, name)



if __name__ == '__main__':
    print COUNTRY_DICT['CN']
    print COUNTRY_DICT['CA']
    print COUNTRY_DICT['US']

    # parse()